repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.8
  hooks:
    # Run check for the linter.
    - id: ruff
      types_or: [ python, pyi ]
    # Run check for the formatter.
    - id: ruff-format
      args: [ --check ]
      types_or: [ python, pyi ]
